### ISSUE TITLE
The server is unable to find the ups

### ISSUE THREAD

**Issue by MrPondi** [fajfer/gcups#12]
Hi, i bought the ups for my qnap nas and i need to get the panel working for the automatic shut off.
I managed to get to the webUI but the ups is not being picked up by the software.
I'm getting the error you put at the bottom of the readme, but even when the device was correct it just kept spamming it
![image](https://github.com/fajfer/gcups/assets/109785648/3a0c566d-f79b-4e8d-896e-ae06374117c8)
At one point i just mounted the whole /dev/bus/usb/ to the container but even that didnt help.
On your blog i saw that some guy had the exact same problem as me so i hope you can help us both

**Comment by fajfer** [comment]
Thanks for the feedback, I've read what you both wrote and I'll try to find some time today/tomorrow and try to replicate that. I'd try plugging the NAS first and then run the image and try it the other way around. I don't think I mentioned it but I think that when I tested different scenarios something like this would happen.

I was also pretty sure that the above error means the web server wouldn't start, I'm going to investigate

For the time being if you don't mind we could try debugging this online sometime. I've just created a room on Matrix: https://matrix.to/#/#gcups:fsfe.org

**Comment by fajfer** [comment]
We've talked it over on Matrix but the author has decided to return the UPS so I couldn't help

**Comment by fajfer** [comment]
Quoting what @maximvdw:matrix.org wrote in our room that could interest some people:

if you have arm64 QNAP NAS users like I saw in one of the issues, recommend them the balves42 docker, if they set it up in container station, the server will run + the device will suddenly be detected on the host as a USB device
